# Generated by Django 5.2.9 on 2025-12-03 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'software',
            },
        ),
        migrations.CreateModel(
            name='StatusEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'status_equipamento',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysinventory.setor')),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('IMPRESSORA', 'Impressora'), ('CELULAR', 'Celular'), ('TABLET', 'Tablet'), ('ROTEADOR', 'Roteador'), ('SWITCH', 'Switch'), ('OUTRO', 'Outro')], max_length=20)),
                ('modelo', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysinventory.funcionario')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysinventory.setor')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysinventory.statusequipamento')),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.CreateModel(
            name='LicencaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200, unique=True)),
                ('tipo_licenca', models.CharField(choices=[('OEM', 'OEM'), ('VOLUME', 'Volume Licensing'), ('SUBSCRIPTION', 'Assinatura'), ('LIFETIME', 'Vitalícia'), ('FREE', 'Gratuita')], max_length=20)),
                ('quantidade_permitida', models.IntegerField(default=1)),
                ('quantidade_usada', models.IntegerField(default=0)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='sysinventory.software')),
            ],
            options={
                'verbose_name': 'Licença de Software',
                'verbose_name_plural': 'Licenças de Software',
                'db_table': 'licenca_software',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CORRETIVA', 'Manutenção Corretiva'), ('PREVENTIVA', 'Manutenção Preventiva'), ('ATUALIZACAO', 'Atualização de Software'), ('LIMPEZA', 'Limpeza Técnica'), ('OUTRO', 'Outro Tipo')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_manutencao', models.DateField()),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='sysinventory.equipamento')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'db_table': 'manutencao',
            },
        ),
        migrations.CreateModel(
            name='HistoricoUsoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_uso', to='sysinventory.equipamento')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_equipamentos', to='sysinventory.funcionario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysinventory.setor')),
            ],
            options={
                'verbose_name': 'Histórico de Uso',
                'verbose_name_plural': 'Históricos de Uso',
                'db_table': 'historico_uso_equipamento',
            },
        ),
        migrations.CreateModel(
            name='LicencaPorEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_instalacao', models.DateField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='sysinventory.equipamento')),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalacoes', to='sysinventory.licencasoftware')),
            ],
            options={
                'db_table': 'licenca_por_equipamento',
                'unique_together': {('licenca', 'equipamento')},
            },
        ),
    ]
